version: '3'
services:
  bushwake:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000" 
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./cmd/api/logs:/app/logs
      - ./config.yml:/app/config.yml
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq-bushwake'
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - ./docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ./docker-conf/rabbitmq/log/:/var/log/rabbitmq
